using System.Runtime.InteropServices;
using System.Windows.Forms;

namespace VolvoWrench
{
    internal class KeyInputApi
    {
        [DllImport("user32.dll")]
        public static extern int GetKeyState(int vKey);
    }

    public class KeyInput
    {
        #region Keys

        [DllImport("user32.dll")]
        public static extern short GetKeyState(Keys nVirtKey);


        public enum VirtualKeyStates
        {
            VkAbntC1 = 0xC1,
            VkAbntC2 = 0xC2,
            VkAdd = 0x6B,
            VkAttn = 0xF6,
            VkBack = 0x08,
            VkCancel = 0x03,
            VkClear = 0x0C,
            VkCrsel = 0xF7,
            VkDecimal = 0x6E,
            VkDivide = 0x6F,
            VkEreof = 0xF9,
            VkEscape = 0x1B,
            VkExecute = 0x2B,
            VkExsel = 0xF8,
            VkIcoClear = 0xE6,
            VkIcoHelp = 0xE3,
            VkKey0 = 0x30,
            VkKey1 = 0x31,
            VkKey2 = 0x32,
            VkKey3 = 0x33,
            VkKey4 = 0x34,
            VkKey6 = 0x36,
            VkKey5 = 0x35,
            VkKey7 = 0x37,
            VkKey8 = 0x38,
            VkKey9 = 0x39,
            VkKeyA = 0x41,
            VkKeyB = 0x42,
            VkKeyC = 0x43,
            VkKeyD = 0x44,
            VkKeyE = 0x45,
            VkKeyF = 0x46,
            VkKeyG = 0x47,
            VkKeyH = 0x48,
            VkKeyI = 0x49,
            VkKeyJ = 0x4A,
            VkKeyK = 0x4B,
            VkKeyL = 0x4C,
            VkKeyM = 0x4D,
            VkKeyN = 0x4E,
            VkKeyO = 0x4F,
            VkKeyP = 0x50,
            VkKeyQ = 0x51,
            VkKeyR = 0x52,
            VkKeyS = 0x53,
            VkKeyT = 0x54,
            VkKeyU = 0x55,
            VkKeyV = 0x56,
            VkKeyW = 0x57,
            VkKeyX = 0x58,
            VkKeyY = 0x59,
            VkKeyZ = 0x5A,
            VkMultiply = 0x6A,
            VkNoname = 0xFC,
            VkNumpad0 = 0x60,
            VkNumpad1 = 0x61,
            VkNumpad2 = 0x62,
            VkNumpad3 = 0x63,
            VkNumpad4 = 0x64,
            VkNumpad5 = 0x65,
            VkNumpad6 = 0x66,
            VkNumpad7 = 0x67,
            VkNumpad8 = 0x68,
            VkNumpad9 = 0x69,
            VkOem1 = 0xBA,
            VkOem102 = 0xE2,
            VkOem2 = 0xBF,
            VkOem3 = 0xC0,
            VkOem4 = 0xDB,
            VkOem5 = 0xDC,
            VkOem6 = 0xDD,
            VkOem7 = 0xDE,
            VkOem8 = 0xDF,
            VkOemAttn = 0xF0,
            VkOemAuto = 0xF3,
            VkOemAx = 0xE1,
            VkOemBacktab = 0xF5,
            VkOemClear = 0xFE,
            VkOemComma = 0xBC,
            VkOemCopy = 0xF2,
            VkOemCusel = 0xEF,
            VkOemEnlw = 0xF4,
            VkOemFinish = 0xF,
            VkOemFjLoya = 0x95,
            VkOemFjMasshou = 0x93,
            VkOemFjRoya = 0x96,
            VkOemFjTouroku = 0x94,
            VkOemJump = 0xEA,
            VkOemMinus = 0xBD,
            VkOemPa1 = 0xEB,
            VkOemPa2 = 0xEC,
            VkOemPa3 = 0xED,
            VkOemPeriod = 0xBE,
            VkOemPlus = 0xBB,
            VkOemReset = 0xE9,
            VkOemWsctrl = 0xE,
            VkPa1 = 0xFD,
            VkPacket = 0xE7,
            VkPlay = 0xFA,
            VkProcesskey = 0xE5,
            VkReturn = 0x0D,
            VkSelect = 0x29,
            VkSeparator = 0x6C,
            VkSpace = 0x20,
            VkSubtract = 0x6D,
            VkTab = 0x09,
            VkZoom = 0xFB,
            VkNone = 0xFF,
            VkAccept = 0x1E,
            VkApps = 0x5D,
            VkBrowserBack = 0xA6,
            VkBrowserFavorites = 0xAB,
            VkBrowserForward = 0xA,
            VkBrowserHome = 0xAC,
            VkBrowserRefresh = 0xA8,
            VkBrowserSearch = 0xAA,
            VkBrowserStop = 0xA9,
            VkCapital = 0x14,
            VkConvert = 0x1C,
            VkDelete = 0x2E,
            VkDown = 0x28,
            VkEnd = 0x23,
            VkF1 = 0x70,
            VkF10 = 0x79,
            VkF11 = 0x7A,
            VkF12 = 0x7B,
            VkF13 = 0x7C,
            VkF14 = 0x7D,
            VkF15 = 0x7E,
            VkF16 = 0x7F,
            VkF17 = 0x80,
            VkF18 = 0x81,
            VkF19 = 0x82,
            VkF2 = 0x71,
            VkF20 = 0x83,
            VkF21 = 0x84,
            VkF22 = 0x85,
            VkF23 = 0x86,
            VkF24 = 0x87,
            VkF3 = 0x72,
            VkF4 = 0x73,
            VkF5 = 0x74,
            VkF6 = 0x75,
            VkF7 = 0x76,
            VkF8 = 0x77,
            VkF9 = 0x78,
            VkFinal = 0x18,
            VkHelp = 0x2F,
            VkHome = 0x24,
            VkIco00 = 0xE4,
            VkInsert = 0x2D,
            VkJunja = 0x17,
            VkKana = 0x15,
            VkKanji = 0x19,
            VkLaunchApp1 = 0xB6,
            VkLaunchApp2 = 0xB7,
            VkLaunchMail = 0xB4,
            VkLaunchMediaSelect = 0xB5,
            VkLbutton = 0x01,
            VkLcontrol = 0xA2,
            VkLeft = 0x25,
            VkLmenu = 0xA4,
            VkLshift = 0xA0,
            VkLwin = 0x5B,
            VkMbutton = 0x04,
            VkMediaNextTrack = 0xB0,
            VkMediaPlayPause = 0xB3,
            VkMediaPrevTrack = 0xB1,
            VkMediaStop = 0xB2,
            VkModechange = 0x1F,
            VkNext = 0x22,
            VkNonconvert = 0x1D,
            VkNumlock = 0x90,
            VkOemFjJisho = 0x92,
            VkPause = 0x13,
            VkPrint = 0x2A,
            VkPrior = 0x21,
            VkRbutton = 0x02,
            VkRcontrol = 0xA3,
            VkRight = 0x27,
            VkRmenu = 0xA5,
            VkRshift = 0xA1,
            VkRwin = 0x5C,
            VkScroll = 0x91,
            VkSleep = 0x5F,
            VkSnapshot = 0x2C,
            VkUp = 0x26,
            VkVolumeDown = 0xAE,
            VkVolumeMute = 0xAD,
            VkVolumeUp = 0xAF,
            VkXbutton1 = 0x05,
            VkXbutton2 = 0x06
        }

        public bool Keystate(Keys key)
        {
            int state = GetKeyState(key);
            return state == -127 || state == -128;
        }
        #endregion
    }
}